### ISSUE TITLE
Attachment handling

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/smtp#11]
We need to send attachments. A new parameter table would be comfy. Do you have any plans for that?
Or maybe the attachment could be put in the body concatenated. Do you have any examples for that?
Thx.

**Comment by Totktonada** [comment]
I didn't try, but with appropriate header and body parts in base64 it should be possible, consider https://stackoverflow.com/questions/44728855/curl-send-html-email-with-embedded-image-and-attachment

**Comment by SWSAmor** [comment]
Thx working that way.

**Comment by Totktonada** [comment]
Anyway it would be good to be able to handle this case via API.
