### ISSUE TITLE
Any 5xx error from SMTP server becomes a strange internal error

### ISSUE THREAD

**Issue by akudiyar** [tarantool/smtp#13]
For example., the server (mock) is set up for returning a 510 code for some sort of e-mails. The server returns "510 Bad email address" in that case. 
On the client side, I want to see the exact response code and error message, but instead I get a runtime error with message "SMTP error 55 (os errno 0)".

The proposed changes to the client: check the response code and return it back with the error message
```
 long response;
 curl_easy_getinfo(handle, CURLINFO_RESPONSE_CODE, response); 
```

**Comment by RunsFor** [comment]
I'm receiving runtime error from smtp client when server sends 3xx,4xx and 5xx status codes:
```
SMTP error 55 (os errno 61)
```

**Comment by RunsFor** [comment]
If SMTP server responds with some weird message, i.e. `'1000 UNKNOWN ERROR\r\n'`, smtp client even **hangs up**.
