### ISSUE TITLE
Doesn't Support Passing Headers

### ISSUE THREAD

**Issue by maiabdelqader** [tarantool/smtp#3]
client = require('smtp').new()

response = client:request(addr, 'sender@tarantool.org',
     'receiver@tarantool.org',
     'mail.body')

There is no option here to add extra email headers except the subject.

**Comment by Totktonada** [comment]
Try to pass `{headers = your_headers_table_here}` as the fourth argument. Enable the verbose output as suggested in #2.

**Comment by Totktonada** [comment]
(that was added in 3e2d3e269cb466b44257d4d1ef212d74faa0fd45)

**Comment by Totktonada** [comment]
@maiabdelqader can you try and confirm the issue can be closed?

**Comment by maiabdelqader** [comment]
Issued has been fixed after updating the module to version 3e2d3e2.

Thanks a lot, closing the issue.
