### ISSUE TITLE
Office365 problem

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/smtp#6]
I try to send mail through Office365. I'm successfully send a mail from command line with curl with something like that:
`curl --connect-timeout 15 -v "smtp://smtp.office365.com:587" -u "hello@example.com:qwertzuiop" -mail-from "hello@example.com" --mail-rcpt "someone@example.com" -T mail.txt --ssl`

> Trying 40.101.19.146...
TCP_NODELAY set
Connected to smtp.office365.com (40.101.19.146) port 587 (#0)
220 AM4PR0202CA0007.outlook.office365.com Microsoft ESMTP MAIL Service ready at Thu, 26 Apr 2018 09:33:58 +0000
EHLO mail.txt
250-AM4PR0202CA0007.outlook.office365.com Hello [185.43.209.9]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8
STARTTLS
220 2.0.0 SMTP server ready

But from Tarantool with the same server, username, password i got something like this:
> Rebuilt URL to: smtp://smtp.office365.com:587/
2018-04-26 09:42:30.966 [44093] main/107/lua I> ping: OK
Trying 40.101.30.242...
TCP_NODELAY set
Connected to smtp.office365.com (40.101.30.242) port 587 (#0)
220 HE1PR0301CA0013.outlook.office365.com Microsoft ESMTP MAIL Service ready at Thu, 26 Apr 2018 08:42:30 +0000
EHLO something
250-HE1PR0301CA0013.outlook.office365.com Hello [185.43.209.9]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8
MAIL FROM:<hello@example.com>
530 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [HE1PR0301CA0013.eurprd03.prod.outlook.com]
MAIL failed: 530
QUIT

Anonymous mail? What cause the problem? Some TLS problem? Missing AUTH LOGIN? I'm stucked. Please help!

**Comment by Totktonada** [comment]
Maybe try to use `smtps://` to enforce TLS?

**Comment by SWSAmor** [comment]
It doesn't seems good:
> Rebuilt URL to: smtps://smtp.office365.com:587/
Trying 40.101.51.162...
TCP_NODELAY set
Connected to smtp.office365.com (40.101.51.162) port 587 (#0)
Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
successfully set certificate verify locations:
CAfile: /etc/ssl/certs/ca-certificates.crt
CApath: /etc/ssl/certs
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Closing connection 0

**Comment by Totktonada** [comment]
How do you set username and password? Can you, please, provide the code example?

**Comment by SWSAmor** [comment]
Here is the code:
```Lua
mail.send = function(pto, pbody, pfrom)
    local from = pfrom or const.MAIL.sender
    local client = smtp.new()
    local response = client:request(const.MAIL.server,
                        from, pto, pbody, const.MAIL.options)
    if not response or not response.status then
        return false, 0
    end
    ttlog.info('mail (send): ' .. json.encode(response))
    return response.status == 250, response.reason
end
```
and the const:
```Lua
const.MAIL = {
	server 	= 'smtp://smtp.office365.com:587',
	options = {
		username 	= 'someone@example.com',
		password 	= 'qwertzuiop',
		verbose		= true
	},
	sender	= 'someone@example.com'
}
```

**Comment by Totktonada** [comment]
Is `pfrom` differs from `const.MAIL.sender`?

**Comment by SWSAmor** [comment]
Nope, default. 
```
mail.send('hello@corp.com', 'Tarantool is cool')
```

**Comment by Totktonada** [comment]
Simple patch to get it working:

```
$ cat /etc/portage/patches/dev-lua/smtp/use-ssl-try.patch
diff --git a/smtp/lib.c b/smtp/lib.c
index abb3770..1d26e2f 100644
--- a/smtp/lib.c
+++ b/smtp/lib.c
@@ -36,6 +36,7 @@
 
 #include <lua.h>
 #include <lauxlib.h>
+#include <curl/curl.h>
 
 #include "module.h"
 #include "smtpc.h"
@@ -157,6 +158,8 @@ luaT_smtpc_request(lua_State *L)
 		smtpc_set_password(req, lua_tostring(L, -1));
 	lua_pop(L, 1);
 
+	curl_easy_setopt(req->easy, CURLOPT_USE_SSL, CURLUSESSL_TRY);
+
 	if (smtpc_execute(req, timeout) != 0) {
 		return luaT_error(L);
 	}
```

I’ll add an option for that or maybe (don’t sure) enable it by default.

**Comment by SWSAmor** [comment]
Patched and works. Thank you!

**Comment by Totktonada** [comment]
@SWSAmor Fixed in the master. Consider to set 'use_ssl = 1` option.
